name: test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: src
      - name: checkout
        uses: actions/checkout@v2
        with:
          repository: ookami-koki/ip_address_msgs
          path: src
        run: ls

      - name: build and test
        run: |
          cd /root/ros2_ws
          bash -xv ./src/mypkg/test/test.bash /root
