name: test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    steps:
      - uses: actions/checkout@v2

      - name: installpip
        run: |
          sudo apt update
          sudo apt install python3-pip -y

      - name: install msgspkg
        run: |
          rsync -av ./ /root/ros2_ws/src/mypkg/
          cd /root/ros2_ws/src
          pip install git+https://github.com/ookami-koki/ip_address_msgs.git
          pwd
          ls -a

      - name: build and test
        run: |
          cd /root/ros2_ws
          bash -xv ./src/mypkg/test/test.bash /root
