name: test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: https://hub.docker.com/repository/docker/ryuichiueda/ubuntu22.04-ros2:latest
    - name: build and test
      run: |
        rsyc -av ./ /root/ros2_ws/src/mypkg/
        cd /root/ros2_ws
        bash -xv ./src/mypkg/test/test.bash /root
