name: test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    steps:
      - name: make mypkg
        uses: actions/checkout@v2
        with:
          path: main
      - name: make ip_address
        uses: actions/checkout@v2
        with:
          repository: ookami-koki/ip_address_msgs
          path: sub
      - name: build and test
        run: |
          cd main
          pwd
          ls
          rsync -av ./ /root/ros2_ws/src/mypkg/
          echo ---------
          cd /__w/mypkg/mypkg/sub
          pwd
          rsync -av ./ /root/ros2_ws/src/ip_address_msgs/
          ls
          echo ---------
          cd
          source ~/.bashrc
          cd /root/ros2_ws
          pwd
          ls
          echo ---------
          bash -xv ./src/mypkg/test/test.bash /root
