name: test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    steps:
      - name: synchro mypkg
        uses: actions/checkout@v2
        with:
          path: main
        run: rsync -av ./ /root/ros2_ws/src/mypkg/
      - name: synchro ip_address
        uses: actions/checkout@v2
        with:
          path: sub
        run: rsync -av ./ /root/ros2_ws/src/ip_address_msgs/
      - name: build and test
        run: |
          pwd
          ls
          cd /root/ros2_ws/src
          pwd
          ls
          cd /root/ros2_ws
          pwd
          ls
          bash -xv ./src/mypkg/test/test.bash /root
